workflows:
  ios-build:
    name: Subtitle Studio iOS Build
    environment:
      xcode: latest
      cocoapods: default
      groups:
        - ios_credentials
    integrations:
      app_store_connect: Codemagic3
    scripts:
      - name: Generate Xcode Project
        script: |
          brew install xcodegen
          xcodegen generate
      - name: Install Dependencies
        script: |
          pod install
      - name: Set up keychain
        script: |
          keychain initialize
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files "com.hmyilm.SubtitleStudio" --type IOS_APP_STORE --create
      - name: Add certificates to keychain
        script: |
          keychain add-certificates
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Build App for TestFlight
        script: |
          xcode-project build-ipa --workspace SubtitleStudio.xcworkspace --scheme SubtitleStudio
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
