name: SubByAudiocraft
options:
  bundleIdPrefix: com.hmyilm
targets:
  SubByAudiocraft:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    version: 1.0.1
    build: 9
    settings:
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      PRODUCT_BUNDLE_IDENTIFIER: com.hmyilm.SubByAudiocraft
      MARKETING_VERSION: "1.0.1"
      CURRENT_PROJECT_VERSION: "9"
    sources: [SubByAudiocraft]
    info:
      path: SubByAudiocraft/Info.plist
      properties:
        UIAppFonts:
          - Anton-Regular.ttf
          - Bangers-Regular.ttf
          - BebasNeue-Regular.ttf
          - Lato-Bold.ttf
          - Pacifico-Regular.ttf
          - PermanentMarker-Regular.ttf
          - Poppins-Bold.ttf
          - Lobster-Regular.ttf
          - Creepster-Regular.ttf
          - AbrilFatface-Regular.ttf
          - AlfaSlabOne-Regular.ttf
          - Righteous-Regular.ttf
          - FrancoisOne-Regular.ttf
          - Shrikhand-Regular.ttf
          - BlackOpsOne-Regular.ttf
        UILaunchScreen: {}
        CFBundleIconName: AppIcon
        CFBundleDisplayName: Sub by Audiocraft
        CFBundleShortVersionString: "1.0.1"
        CFBundleVersion: "9"
        ITSAppUsesNonExemptEncryption: false
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSPhotoLibraryUsageDescription: "Videolarınızı işleyebilmek için fotoğraf galerinize erişmemiz gerekiyor."
        NSPhotoLibraryAddUsageDescription: "Oluşturulan altyazılı videoyu galerinize kaydetmek için izin gerekiyor."
        NSSpeechRecognitionUsageDescription: "Videodaki sözleri otomatik yakalamak için ses tanıma izni gereklidir."
        NSMicrophoneUsageDescription: "Ses tanıma algoritması için gereklidir."
        NSCameraUsageDescription: "Uygulama altyapısı, video işleme motoru için kamera erişim iznine ihtiyaç duymaktadır."
