name: SubByAudiocraft
options:
  bundleIdPrefix: com.hmyilm
packages:
  WhisperKit:
    url: https://github.com/argmaxinc/WhisperKit
    from: 0.7.2
targets:
  SubByAudiocraft:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    version: 1.2.0
    build: 15
    settings:
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      PRODUCT_BUNDLE_IDENTIFIER: com.hmyilm.SubByAudiocraft
      MARKETING_VERSION: "1.2.0"
      CURRENT_PROJECT_VERSION: "15"
    sources: [SubByAudiocraft]
    dependencies:
      - package: WhisperKit
    info:
      path: SubByAudiocraft/Info.plist
      properties:
        UIAppFonts:
          - Anton-Regular.ttf
          - Bangers-Regular.ttf
          - BebasNeue-Regular.ttf
          - Lato-Bold.ttf
          - Pacifico-Regular.ttf
          - PermanentMarker-Regular.ttf
          - Poppins-Bold.ttf
          - Lobster-Regular.ttf
          - Creepster-Regular.ttf
          - AbrilFatface-Regular.ttf
          - AlfaSlabOne-Regular.ttf
          - Righteous-Regular.ttf
          - FrancoisOne-Regular.ttf
          - Shrikhand-Regular.ttf
          - BlackOpsOne-Regular.ttf
        UILaunchScreen: {}
        CFBundleIconName: AppIcon
        CFBundleDisplayName: Sub by Audiocraft
        CFBundleShortVersionString: "1.2.0"
        CFBundleVersion: "15"
        ITSAppUsesNonExemptEncryption: false
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSPhotoLibraryUsageDescription: "Videolarınızı işleyebilmek için fotoğraf galerinize erişmemiz gerekiyor."
        NSPhotoLibraryAddUsageDescription: "Oluşturulan altyazılı videoyu galerinize kaydetmek için izin gerekiyor."
